# -*- coding: utf-8 -*-
"""Privacy-safe, execution-checkout-bound ChatGPT Action H1 evidence.

This module performs no network, Telegram, HOSTiQ, credential or production
mutation. It compares an externally captured/sanitized OpenAPI document with
the exact schema generated by the same clean Git checkout that contains and is
executing this evidence code. Candidate identity is derived from Git; callers
cannot supply or relabel a SHA and cannot point this running tool at another
clean checkout to relabel the executing schema implementation.

A matching result is evidence input for H1 only. It never self-authorizes H1,
deployment, K5, or any live operation, and a ``DEPLOYED_CAPTURE`` label remains
caller-authored until an independent live/runtime gate adjudicates provenance.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import subprocess
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import urlsplit

from ops import dev06_api_contracts as _api_contracts_module
from ops import dev06_runtime_conformance as _runtime_conformance_module
from ops.dev06_api_contracts import CANONICAL_ROUTES, ApiExposure
from ops.dev06_runtime_conformance import (
    ResponseContractError,
    build_compatible_chatgpt_action_openapi,
    validate_action_compatibility,
)


PRODUCTION_BASE_URL = "https://tg-api.rukadopomogy.org.ua"
MAX_SCHEMA_BYTES = 1024 * 1024
_ALLOWED_SOURCE_CLASSIFICATIONS = {"SOURCE_MOCK", "DEPLOYED_CAPTURE"}
_ALLOWED_MISMATCH_CODES = frozenset({
    "DOCUMENT_DIGEST_DRIFT",
    "OBSERVED_SCHEMA_VALIDATION_FAILED",
    "OPERATION_CONTRACT_DRIFT",
    "OPERATION_COUNT_DRIFT",
    "PATH_SET_DRIFT",
    "ROOT_SECURITY_DRIFT",
    "SERVER_ORIGIN_DRIFT",
})
_SHA40_RE = re.compile(r"^[0-9a-f]{40}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class DeployedActionEvidenceError(ResponseContractError):
    """Fail-closed deployed Action comparison error with stable public codes."""


def _run_git(root: Path, *args: str, text: bool = True) -> str | bytes:
    try:
        proc = subprocess.run(
            ["git", *args],
            cwd=root,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=text,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_GIT_UNAVAILABLE") from None
    if proc.returncode != 0:
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_GIT_UNAVAILABLE")
    return proc.stdout


def _source_root(source_checkout: str | os.PathLike[str] | Path) -> Path:
    try:
        raw = Path(source_checkout)
        info = raw.lstat()
        if not stat.S_ISDIR(info.st_mode) or raw.is_symlink():
            raise OSError
        root = raw.resolve(strict=True)
    except (OSError, TypeError, ValueError):
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_UNSAFE") from None
    top = str(_run_git(root, "rev-parse", "--show-toplevel")).strip()
    try:
        top_root = Path(top).resolve(strict=True)
    except OSError:
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_UNSAFE") from None
    if top_root != root:
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_NOT_REPOSITORY_ROOT")
    return root


def _execution_checkout_root() -> Path:
    """Bind schema-generating imports to one exact repository root.

    H1/H2 expected schema bytes are produced by imported canonical modules.  It
    is therefore insufficient to derive a SHA from an arbitrary clean checkout:
    the supplied checkout must be the very checkout containing this module and
    the schema-generating modules imported by this process.
    """

    module_files = (
        __file__,
        getattr(_api_contracts_module, "__file__", None),
        getattr(_runtime_conformance_module, "__file__", None),
    )
    roots: list[Path] = []
    for value in module_files:
        if not isinstance(value, str) or not value:
            raise DeployedActionEvidenceError("SOURCE_EXECUTION_MODULE_MISMATCH")
        try:
            file_path = Path(value).resolve(strict=True)
            roots.append(file_path.parents[1])
        except (OSError, IndexError):
            raise DeployedActionEvidenceError("SOURCE_EXECUTION_MODULE_MISMATCH") from None
    if len(set(roots)) != 1:
        raise DeployedActionEvidenceError("SOURCE_EXECUTION_MODULE_MISMATCH")
    root = roots[0]
    top = str(_run_git(root, "rev-parse", "--show-toplevel")).strip()
    try:
        top_root = Path(top).resolve(strict=True)
    except OSError:
        raise DeployedActionEvidenceError("SOURCE_EXECUTION_MODULE_MISMATCH") from None
    if top_root != root:
        raise DeployedActionEvidenceError("SOURCE_EXECUTION_MODULE_MISMATCH")
    return root


def _require_clean_tracked_tree(root: Path) -> None:
    for args in (
        ("diff", "--quiet", "--no-ext-diff", "HEAD", "--"),
        ("diff", "--cached", "--quiet", "--no-ext-diff", "HEAD", "--"),
    ):
        try:
            proc = subprocess.run(
                ["git", *args],
                cwd=root,
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=30,
            )
        except (OSError, subprocess.SubprocessError):
            raise DeployedActionEvidenceError("SOURCE_CHECKOUT_GIT_UNAVAILABLE") from None
        if proc.returncode == 1:
            raise DeployedActionEvidenceError("SOURCE_CHECKOUT_TRACKED_TREE_DIRTY")
        if proc.returncode != 0:
            raise DeployedActionEvidenceError("SOURCE_CHECKOUT_GIT_UNAVAILABLE")


def derive_source_binding(source_checkout: str | os.PathLike[str] | Path) -> dict[str, Any]:
    """Derive exact candidate identity from the clean executing checkout.

    The supplied checkout must be the execution checkout. To inspect a different
    candidate, execute this evidence tool from that candidate checkout instead
    of asking one checkout to label another.
    """

    root = _source_root(source_checkout)
    if root != _execution_checkout_root():
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_EXECUTION_MISMATCH")
    _require_clean_tracked_tree(root)
    sha = str(_run_git(root, "rev-parse", "--verify", "HEAD^{commit}")).strip()
    tree_sha = str(_run_git(root, "rev-parse", "--verify", "HEAD^{tree}")).strip()
    listing = _run_git(root, "ls-tree", "-r", "-z", "--full-tree", "HEAD", text=False)
    if (
        not isinstance(listing, bytes)
        or not listing
        or _SHA40_RE.fullmatch(sha) is None
        or _SHA40_RE.fullmatch(tree_sha) is None
    ):
        raise DeployedActionEvidenceError("SOURCE_CHECKOUT_IDENTITY_INVALID")
    base = {
        "schema_version": 1,
        "identity_source": "EXECUTING_EXACT_GIT_CHECKOUT",
        "candidate_sha": sha,
        "source_tree_sha": tree_sha,
        "source_tree_listing_sha256": hashlib.sha256(listing).hexdigest(),
        "private_values_recorded": False,
    }
    binding_digest = hashlib.sha256(
        json.dumps(base, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")
    ).hexdigest()
    return {**base, "source_binding_sha256": binding_digest}


def _validate_source_binding(
    binding: Mapping[str, Any], source_checkout: str | os.PathLike[str] | Path
) -> dict[str, Any]:
    expected = derive_source_binding(source_checkout)
    if not isinstance(binding, Mapping) or dict(binding) != expected:
        raise DeployedActionEvidenceError("SOURCE_BINDING_MISMATCH")
    return expected


def _require_source_classification(value: str) -> str:
    raw = str(value or "").strip().upper()
    if raw not in _ALLOWED_SOURCE_CLASSIFICATIONS:
        raise DeployedActionEvidenceError("SOURCE_CLASSIFICATION_INVALID")
    return raw


def _require_base_url(value: str) -> str:
    raw = str(value or "").strip()
    parts = urlsplit(raw)
    if (
        parts.scheme != "https"
        or not parts.netloc
        or parts.username is not None
        or parts.password is not None
        or parts.query
        or parts.fragment
        or parts.path not in {"", "/"}
    ):
        raise DeployedActionEvidenceError("BASE_URL_INVALID")
    normalized = raw[:-1] if raw.endswith("/") else raw
    if normalized != PRODUCTION_BASE_URL:
        raise DeployedActionEvidenceError("BASE_URL_NOT_PRODUCTION")
    return normalized


def canonical_json_bytes(document: Mapping[str, Any]) -> bytes:
    if not isinstance(document, Mapping):
        raise DeployedActionEvidenceError("SCHEMA_DOCUMENT_NOT_OBJECT")
    try:
        encoded = json.dumps(
            document,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError, UnicodeError):
        raise DeployedActionEvidenceError("SCHEMA_DOCUMENT_NOT_CANONICAL_JSON") from None
    if not encoded or len(encoded) > MAX_SCHEMA_BYTES:
        raise DeployedActionEvidenceError("SCHEMA_DOCUMENT_SIZE_INVALID")
    return encoded


def schema_sha256(document: Mapping[str, Any]) -> str:
    return hashlib.sha256(canonical_json_bytes(document)).hexdigest()


def _origin_sha256(base_url: str) -> str:
    return hashlib.sha256(base_url.encode("utf-8")).hexdigest()


def _declared_operation_count(document: Mapping[str, Any]) -> int:
    paths = document.get("paths")
    if not isinstance(paths, Mapping):
        return 0
    count = 0
    for item in paths.values():
        if not isinstance(item, Mapping):
            continue
        for operation in item.values():
            if isinstance(operation, Mapping) and isinstance(operation.get("operationId"), str):
                count += 1
    return count


def _expected_action_routes() -> tuple[Any, ...]:
    return tuple(route for route in CANONICAL_ROUTES if route.exposure is ApiExposure.ACTION)


def _operation_drift_count(expected: Mapping[str, Any], observed: Mapping[str, Any]) -> int:
    expected_paths = expected.get("paths")
    observed_paths = observed.get("paths")
    if not isinstance(expected_paths, Mapping) or not isinstance(observed_paths, Mapping):
        return len(_expected_action_routes())
    drift = 0
    for route in _expected_action_routes():
        exp_item = expected_paths.get(route.path)
        obs_item = observed_paths.get(route.path)
        exp_op = exp_item.get("post") if isinstance(exp_item, Mapping) else None
        obs_op = obs_item.get("post") if isinstance(obs_item, Mapping) else None
        if not isinstance(exp_op, Mapping) or not isinstance(obs_op, Mapping):
            drift += 1
            continue
        try:
            if canonical_json_bytes(exp_op) != canonical_json_bytes(obs_op):
                drift += 1
        except DeployedActionEvidenceError:
            drift += 1
    return drift


def _path_set(document: Mapping[str, Any]) -> set[str] | None:
    paths = document.get("paths")
    if not isinstance(paths, Mapping):
        return None
    return {str(path) for path in paths}


def _server_list(document: Mapping[str, Any]) -> Any:
    return document.get("servers")


def _root_security(document: Mapping[str, Any]) -> Any:
    return document.get("security")


def compare_deployed_action_schema(
    source_checkout: str | os.PathLike[str] | Path,
    observed_document: Mapping[str, Any],
    *,
    base_url: str = PRODUCTION_BASE_URL,
    source_classification: str = "SOURCE_MOCK",
) -> dict[str, Any]:
    """Compare expected vs captured schema with execution-checkout identity."""

    binding = derive_source_binding(source_checkout)
    source = _require_source_classification(source_classification)
    origin = _require_base_url(base_url)
    expected = build_compatible_chatgpt_action_openapi(origin)

    expected_bytes = canonical_json_bytes(expected)
    observed_bytes = canonical_json_bytes(observed_document)
    expected_digest = hashlib.sha256(expected_bytes).hexdigest()
    observed_digest = hashlib.sha256(observed_bytes).hexdigest()

    mismatch_codes: list[str] = []
    try:
        observed_validation = validate_action_compatibility(observed_document)
    except Exception:
        observed_validation = ["invalid"]
    if observed_validation:
        mismatch_codes.append("OBSERVED_SCHEMA_VALIDATION_FAILED")
    if _path_set(expected) != _path_set(observed_document):
        mismatch_codes.append("PATH_SET_DRIFT")
    if _server_list(expected) != _server_list(observed_document):
        mismatch_codes.append("SERVER_ORIGIN_DRIFT")
    if _root_security(expected) != _root_security(observed_document):
        mismatch_codes.append("ROOT_SECURITY_DRIFT")

    expected_operation_count = _declared_operation_count(expected)
    observed_operation_count = _declared_operation_count(observed_document)
    if expected_operation_count != observed_operation_count:
        mismatch_codes.append("OPERATION_COUNT_DRIFT")

    operation_drift_count = _operation_drift_count(expected, observed_document)
    if operation_drift_count:
        mismatch_codes.append("OPERATION_CONTRACT_DRIFT")
    if expected_digest != observed_digest:
        mismatch_codes.append("DOCUMENT_DIGEST_DRIFT")

    mismatch_codes = sorted(set(mismatch_codes))
    schema_match = not mismatch_codes and expected_digest == observed_digest
    summary: dict[str, Any] = {
        "schema_version": 2,
        "candidate_sha": binding["candidate_sha"],
        "source_tree_sha": binding["source_tree_sha"],
        "source_tree_listing_sha256": binding["source_tree_listing_sha256"],
        "source_binding_sha256": binding["source_binding_sha256"],
        "source_classification": source,
        "server_origin_sha256": _origin_sha256(origin),
        "expected_schema_sha256": expected_digest,
        "observed_schema_sha256": observed_digest,
        "expected_schema_bytes": len(expected_bytes),
        "observed_schema_bytes": len(observed_bytes),
        "expected_operation_count": expected_operation_count,
        "observed_operation_count": observed_operation_count,
        "operation_drift_count": operation_drift_count,
        "mismatch_count": len(mismatch_codes),
        "mismatch_codes": mismatch_codes,
        "schema_match": schema_match,
        "product_h1_pass": False,
        "deployment_authorized": False,
        "production_mutated": False,
        "private_values_recorded": False,
    }
    validate_evidence_summary(summary, source_checkout)
    return summary


def validate_evidence_summary(
    summary: Mapping[str, Any], source_checkout: str | os.PathLike[str] | Path
) -> None:
    required = {
        "schema_version", "candidate_sha", "source_tree_sha", "source_tree_listing_sha256",
        "source_binding_sha256", "source_classification", "server_origin_sha256",
        "expected_schema_sha256", "observed_schema_sha256", "expected_schema_bytes",
        "observed_schema_bytes", "expected_operation_count", "observed_operation_count",
        "operation_drift_count", "mismatch_count", "mismatch_codes", "schema_match",
        "product_h1_pass", "deployment_authorized", "production_mutated",
        "private_values_recorded",
    }
    if not isinstance(summary, Mapping) or set(summary) != required:
        raise DeployedActionEvidenceError("EVIDENCE_SUMMARY_SHAPE_INVALID")
    if summary.get("schema_version") != 2:
        raise DeployedActionEvidenceError("EVIDENCE_SCHEMA_VERSION_INVALID")

    binding = derive_source_binding(source_checkout)
    for key in (
        "candidate_sha", "source_tree_sha", "source_tree_listing_sha256", "source_binding_sha256"
    ):
        if summary.get(key) != binding[key]:
            raise DeployedActionEvidenceError("EVIDENCE_SOURCE_BINDING_INVALID")
    _require_source_classification(summary["source_classification"])

    for key in (
        "source_tree_listing_sha256", "source_binding_sha256", "server_origin_sha256",
        "expected_schema_sha256", "observed_schema_sha256",
    ):
        value = summary.get(key)
        if not isinstance(value, str) or _SHA256_RE.fullmatch(value) is None:
            raise DeployedActionEvidenceError("EVIDENCE_DIGEST_INVALID")
    if _SHA40_RE.fullmatch(str(summary.get("candidate_sha", ""))) is None or _SHA40_RE.fullmatch(
        str(summary.get("source_tree_sha", ""))
    ) is None:
        raise DeployedActionEvidenceError("EVIDENCE_SOURCE_BINDING_INVALID")

    for key in (
        "expected_schema_bytes", "observed_schema_bytes", "expected_operation_count",
        "observed_operation_count", "operation_drift_count", "mismatch_count",
    ):
        value = summary.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            raise DeployedActionEvidenceError("EVIDENCE_COUNT_INVALID")
    if (
        summary["expected_schema_bytes"] > MAX_SCHEMA_BYTES
        or summary["observed_schema_bytes"] > MAX_SCHEMA_BYTES
        or summary["expected_operation_count"] > 1024
        or summary["observed_operation_count"] > 1024
        or summary["operation_drift_count"] > 1024
        or summary["mismatch_count"] > len(_ALLOWED_MISMATCH_CODES)
    ):
        raise DeployedActionEvidenceError("EVIDENCE_COUNT_INVALID")

    codes = summary.get("mismatch_codes")
    if (
        not isinstance(codes, list)
        or len(codes) > len(_ALLOWED_MISMATCH_CODES)
        or any(code not in _ALLOWED_MISMATCH_CODES for code in codes)
        or codes != sorted(set(codes))
    ):
        raise DeployedActionEvidenceError("EVIDENCE_MISMATCH_CODES_INVALID")
    if summary["mismatch_count"] != len(codes):
        raise DeployedActionEvidenceError("EVIDENCE_MISMATCH_COUNT_INVALID")

    for key in (
        "schema_match", "product_h1_pass", "deployment_authorized",
        "production_mutated", "private_values_recorded",
    ):
        if not isinstance(summary.get(key), bool):
            raise DeployedActionEvidenceError("EVIDENCE_BOOLEAN_INVALID")
    if any(summary[key] for key in (
        "product_h1_pass", "deployment_authorized", "production_mutated", "private_values_recorded"
    )):
        raise DeployedActionEvidenceError("EVIDENCE_MUST_NOT_SELF_AUTHORIZE_OR_RECORD_PRIVATE_VALUES")

    expected_document = build_compatible_chatgpt_action_openapi(PRODUCTION_BASE_URL)
    expected_bytes = canonical_json_bytes(expected_document)
    expected_digest = hashlib.sha256(expected_bytes).hexdigest()
    expected_operation_count = _declared_operation_count(expected_document)
    if summary["server_origin_sha256"] != _origin_sha256(PRODUCTION_BASE_URL):
        raise DeployedActionEvidenceError("EVIDENCE_ORIGIN_BINDING_INVALID")
    if (
        summary["expected_schema_sha256"] != expected_digest
        or summary["expected_schema_bytes"] != len(expected_bytes)
        or summary["expected_operation_count"] != expected_operation_count
    ):
        raise DeployedActionEvidenceError("EVIDENCE_SOURCE_SCHEMA_BINDING_INVALID")

    derived_match = bool(
        summary["mismatch_count"] == 0
        and summary["expected_schema_sha256"] == summary["observed_schema_sha256"]
        and summary["expected_schema_bytes"] == summary["observed_schema_bytes"]
        and summary["expected_operation_count"] == summary["observed_operation_count"]
        and summary["operation_drift_count"] == 0
    )
    if summary["schema_match"] is not derived_match:
        raise DeployedActionEvidenceError("EVIDENCE_MATCH_STATE_INVALID")


def _stat_fingerprint(info: os.stat_result) -> tuple[int, int, int, int, int, int, int]:
    return (
        info.st_dev,
        info.st_ino,
        info.st_mode,
        info.st_nlink,
        info.st_size,
        getattr(info, "st_mtime_ns", int(info.st_mtime * 1_000_000_000)),
        getattr(info, "st_ctime_ns", int(info.st_ctime * 1_000_000_000)),
    )


def load_observed_schema(path: str | Path) -> Mapping[str, Any]:
    """Read one bounded regular no-follow JSON file without exposing its path."""

    raw_path = os.fspath(path)
    flags = os.O_RDONLY
    if hasattr(os, "O_CLOEXEC"):
        flags |= os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        fd = os.open(raw_path, flags)
    except OSError:
        raise DeployedActionEvidenceError("OBSERVED_SCHEMA_FILE_UNSAFE") from None
    try:
        before = os.fstat(fd)
        if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1 or before.st_size <= 0 or before.st_size > MAX_SCHEMA_BYTES:
            raise DeployedActionEvidenceError("OBSERVED_SCHEMA_FILE_UNSAFE")
        chunks: list[bytes] = []
        remaining = MAX_SCHEMA_BYTES + 1
        while remaining > 0:
            chunk = os.read(fd, min(65536, remaining))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        if len(data) > MAX_SCHEMA_BYTES:
            raise DeployedActionEvidenceError("OBSERVED_SCHEMA_FILE_TOO_LARGE")
        after = os.fstat(fd)
        if _stat_fingerprint(before) != _stat_fingerprint(after) or len(data) != before.st_size:
            raise DeployedActionEvidenceError("OBSERVED_SCHEMA_FILE_CHANGED_DURING_READ")
    finally:
        os.close(fd)
    try:
        parsed = json.loads(data.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError):
        raise DeployedActionEvidenceError("OBSERVED_SCHEMA_JSON_INVALID") from None
    if not isinstance(parsed, Mapping):
        raise DeployedActionEvidenceError("OBSERVED_SCHEMA_JSON_NOT_OBJECT")
    canonical_json_bytes(parsed)
    return parsed
